#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# get METIS_VERSION, METIS_ARCH_PATH
if settings=`$WM_PROJECT_DIR/bin/foamEtcFile config.sh/parmetis`
then
    . $settings
    echo "    using PARMETIS_ARCH_PATH=$PARMETIS_ARCH_PATH"
    if [ -r $PARMETIS_ARCH_PATH/lib/libparmetis.so ]
    then
        wmake $targetType
    fi
else
    echo
    echo "    Error: no config.sh/parmetis settings"
    echo
fi


#------------------------------------------------------------------------------
