#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

#------------------------------------------------------------------------------

wclean metisDecomp
wclean parmetisDecomp
wclean kahipDecomp
wclean scotchDecomp
wclean decompositionMethods
wclean decompose
wclean faDecompose

./Allwclean-mpi

#------------------------------------------------------------------------------
