#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

wmake $targetType scotchDecomp
wmake $targetType ptscotchDecomp
wmake $targetType metisDecomp
wmake $targetType parmetisDecomp
wmake $targetType kahipDecomp
wmake $targetType MGridGen

#------------------------------------------------------------------------------
